[package]
name = "qce_kernels"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "qce_kernels"
path = "src/lib.rs"

[features]
default = []
fast-math = []

[dependencies]
